### ISSUE TITLE
섬 꾸미기 관련 API

### ISSUE THREAD

**Issue by 0321minji** [0321minji/Cognisle_BE#24]
- [x] 로직 이해하기

![Image](https://github.com/0321minji/Cognisle_BE/assets/67853616/95172345-0c6c-4212-9d86-d8d7ed747ce2)

섬(lands) 및 아이템 모델
![Image](https://github.com/0321minji/Cognisle_BE/assets/79096808/dd074f6c-bdc1-4d56-9eef-b71c78c2671f)
아이템 이미지는 공통으로 사용되는 거라서 따로 빼고
- 아이템 모델이 생성되면 user 랑 연결하는 방식 (item 모델 생성 = user가 획득한 아이템) : 유저가 지닌 아이템 list api
- 아이템이 show이면 사용한 아이템(t/f) : show가 false인 아이템 list api(위 사진에서의 d)
- 아이템 - locatrion(x,y,z)연결  

![Image](https://github.com/0321minji/Cognisle_BE/assets/79096808/bc6ecf56-c6c6-4956-82fd-2e707d89e466)

- item list api 작성 : 보유하고 있는 모든 아이템 list 가져옴

![Image](https://github.com/0321minji/Cognisle_BE/assets/79096808/df73cc4d-15ce-4456-9f14-cbac3f5517dd)

- 서버에 배포 후 확인 완료

![Image](https://github.com/0321minji/Cognisle_BE/assets/79096808/07323f75-7569-4be6-ab22-338ec241f086)

- item show update api 작성 : item 의 show를 update하는 api 
  show -> unshow (show=False), unshow-> show(show=True)로 수정

- [ ] API 명세서 작성 > swagger 연결 예정
- [ ] 이미지 소스 전달 (@@JangAyeon )

**Comment by JangAyeon** [comment]
**꾸미기**
섬 + 아이템 동시에 하는 말!!

**소유했지만 위치 설정 안한 아이템**
show: false
위치 정보: 아무값으로 (추후 화면에 나올 기본 위치 값으로 변경)

**꾸미기 상태 조회**
- 섬타임 & 아이템 상태 한번에 나오는 게 편함
- n개 아이템 중 소유한 아이템만 나옴

**사용자 꾸미기 상태 조회 API**
1. 유저 계정 연결 토큰 설정
2. 아이템/섬 이미지 URL

**사용자 꾸미기 상태 수정 API**
x개 아이템을 사용한 클라이언트 측 꾸미기 상태를 서버로 전달

**Comment by 0321minji** [comment]
꾸미기 상태 조회


![Image](https://github.com/0321minji/Cognisle_BE/assets/79096808/a70b37dd-2a69-4c7a-9dc3-b6483809e742)

로그인 한 유저가 자신의 lands 꾸미기 상태 조회 가능
- 일단 다른 유저의 lands 접근 시, permission denied 되도록 설정해둠
- background 값(1~3)에 따라 (섬 img와 배경 img) 불러옴
- show true이면(사용했으면) locations 도 같이 return 
- show false이면(사용안했으면) locations 없이 return

**Comment by 0321minji** [comment]
- [ ] urls에서 lands에 대한 pk 값 빼기, body로 전달(다른 사람이 url 임의 조정 가능하므로) , item 관련 api들도 수정
- [ ] swagger 연결 및 전달
- [ ] 이모지 체크된 파일들 보고 확인

**Comment by 0321minji** [comment]
- 섬 방문 api (lands/<userid>/)는 GET 방식이라서 body 사용 X
->
